[book]
authors = ["Optimism Contributors"]
language = "en"
multilingual = false
src = "src"
title = "OP Stack Smart Contracts"

[output.html]
site-url = "/contracts-bedrock/"
git-repository-url = "https://github.com/cpchain-network/cp-chain/tree/develop/packages/contracts-bedrock/book"
edit-url-template = "https://github.com/cpchain-network/cp-chain/tree/develop/packages/contracts-bedrock/book/{path}"
additional-css = ["custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
